# This list provides the prompts for our dataset generator.
# We're aiming for 100 diverse recipes from various regions.

RECIPE_NAMES = [
    # --- North Indian ---
    "Paneer Tikka Masala",
    "Butter Chicken (Murgh Makhani)",
    "Rogan Josh",
    "Malai Kofta",
    "Aloo Paratha",
    "Chole Bhature",
    "Rajma Chawal",
    "Sarson Ka Saag",
    "Makki Di Roti",
    "Kadai Paneer",
    "Nihari Gosht",
    "Dum Aloo",
    "Shahi Paneer",
    "Kashmiri Pulao",
    "Naan Bread",
    "Garlic Naan",
    "Keema Matar",
    "Tandoori Chicken",
    "Seekh Kebab",
    "Mutter Paneer",
    "Amritsari Fish Fry",
    "Paneer Butter Masala",
    "Kadhi Chawal",
    "Bhature Chole Kulcha",
    "Gatte Ki Sabzi",
    "Ker Sangri",
    "Laal Maas",
    "Besan Chilla",
    "Bathua Raita",
    "Aloo Gobhi",
    "Palak Paneer",
    "Pindi Chole",
    "Aloo Tikki Chaat",
    "Dahi Bhalla",
    "Papdi Chaat",
    "Kachori Sabzi",
    "Bedmi Puri",
    "Banarasi Dum Aloo",
    "Mathura Peda",
    "Kanji Vada",
    "Kachumber Salad",
    "Rajasthani Kadhi",
    "Mooli Paratha",
    "Paneer Bhurji",
    "Dal Baati Churma",
    "Moong Dal Halwa",
    "Bharwa Bhindi",
    "Tandoori Roti",
    "Stuffed Capsicum",
    "Chana Dal Tadka",

    # --- South Indian ---
    "Hyderabadi Biryani",
    "Masala Dosa",
    "Idli Sambar",
    "Vada Sambar",
    "Coconut Chutney",
    "Tomato Chutney",
    "Chettinad Chicken",
    "Kerala Prawn Curry",
    "Avial (Mixed Vegetable Curry)",
    "Bisi Bele Bath",
    "Lemon Rice",
    "Tamarind Rice (Puliyogare)",
    "Rava Upma",
    "Appam with Coconut Milk",
    "Mysore Pak",
    "Pesarattu (Green Gram Dosa)",
    "Kuzhi Paniyaram",
    "Ulli Theeyal (Shallot Curry)",
    "Puttu and Kadala Curry",
    "Rasam",
    "Sambar Rice",
    "Pongal",
    "Ven Pongal",
    "Adai Dosa",
    "Idiyappam",
    "Thayir Sadam (Curd Rice)",
    "Chettinad Pepper Chicken",
    "Kootu Curry",
    "Vegetable Stew",
    "Kappa and Meen Curry",
    "Meen Pollichathu",
    "Mutton Sukka",
    "Kozhi Varuval",
    "Erachi Varattiyathu",
    "Uppittu",
    "Kesari Bath",
    "Olan (Ash Gourd Curry)",
    "Pulissery",
    "Vatha Kuzhambu",
    "Ragi Mudde",
    "Chicken 65",
    "Mutton Biryani (Ambur Style)",
    "Egg Curry Kerala Style",
    "Beef Ularthiyathu",
    "Mangalore Fish Curry",
    "Neer Dosa",
    "Korri Gassi",
    "Sajjige Bajil",
    "Ragi Dosa",
    "Mysore Rasam",
    "Set Dosa",
    "Noolappam",
    "Pesarapappu Pulusu",
    "Andhra Chicken Curry",
    "Gongura Mutton",
    "Gutti Vankaya Curry",
    "Chepa Pulusu",
    "Kodi Kura",
    "Ulavacharu (Horse Gram Soup)",

    # --- East Indian ---
    "Machher Jhol (Bengali Fish Curry)",
    "Litti Chokha",
    "Shorshe Ilish (Hilsa in Mustard)",
    "Chingri Malai Curry (Prawn Curry)",
    "Rasgulla",
    "Sandesh",
    "Kosha Mangsho (Bengali Mutton)",
    "Dalma (Odisha Dal)",
    "Ghugni (Dried Peas Curry)",
    "Thekua (Bihari Sweet)",
    "Pitha (Assamese Rice Cake)",
    "Momos (Sikkimese Dumpling)",
    "Macher Kalia",
    "Beguni (Brinjal Fritter)",
    "Aloo Posto",
    "Cholar Dal",
    "Bengali Chingri Cutlet",
    "Bhetki Paturi",
    "Kacha Golla",
    "Misti Doi",
    "Labra (Mixed Veg Curry)",
    "Mochar Ghonto",
    "Prawn Malai Curry",
    "Chicken Rezala",
    "Egg Devil",
    "Jhuri Aloo Bhaja",
    "Pakhala Bhata (Fermented Rice)",
    "Santula (Odisha Veg Curry)",
    "Chenna Poda",
    "Khaja (Odisha Sweet)",
    "Thukpa",
    "Thenthuk (Tibetan Noodle Soup)",
    "Smoked Pork with Bamboo Shoot",
    "Axone Pork",
    "Eromba (Manipur Dish)",
    "Singju (Manipuri Salad)",
    "Aloo Pitika (Assam)",
    "Fish Tenga (Tangy Fish Curry)",
    "Khura (Arunachal Pancake)",
    "Chak Hao Kheer (Black Rice Pudding)",
    "Khar (Assamese Alkaline Curry)",
    "Pitha (Bihu Special)",
    "Ros Bora (Bengal Sweet Dumpling)",
    "Bora Diya Masor Tenga",

    # --- West Indian ---
    "Pav Bhaji",
    "Vada Pav",
    "Goan Fish Curry",
    "Chicken Xacuti",
    "Pork Vindaloo",
    "Khaman Dhokla",
    "Khandvi",
    "Thepla",
    "Undhiyu",
    "Modak (Ukadiche)",
    "Shrikhand",
    "Puran Poli",
    "Bombil Fry (Bombay Duck)",
    "Misal Pav",
    "Zunka Bhakar",
    "Sev Usal",
    "Dal Dhokli",
    "Handvo",
    "Patra (Alu Vadi)",
    "Surti Undhiyu",
    "Bhaat Na Rasawala Bataka",
    "Lasaniya Batata",
    "Goan Sorpotel",
    "Bebinca",
    "Goan Sausage Pulao",
    "Khatkhate (Goan Mixed Veg Stew)",
    "Bombay Sandwich",
    "Frankie Roll",
    "Dabeli",
    "Sev Puri",
    "Bhel Puri",
    "Ragda Pattice",
    "Kolhapuri Chicken",
    "Kolhapuri Tambda Rassa",
    "Pandhra Rassa",
    "Solkadhi",
    "Sabudana Khichdi",
    "Thalipeeth",
    "Pitla Bhakri",
    "Matki Usal",
    "Poha",
    "Sheera",
    "Batata Vada",
    "Kombdi Vade",
    "Pathrode",
    "Chicken Cafreal",
    "Fish Recheado",
    "Sorak Curry",
    "Goan Mushroom Xacuti",
    "Shrimp Balchão",
    "Goan Prawn Pulao",
    "Guvar Bhaji",
    "Moog Usal",
    "Kanda Poha",

    # --- General / Vegetarian ---
    "Bhindi Masala (Okra)",
    "Baingan Bharta (Roasted Eggplant)",
    "Navratan Korma",
    "Gobi Manchurian",
    "Vegetable Korma",
    "Mushroom Masala",
    "Baby Corn Masala",
    "Methi Malai Matar",
    "Aloo Matar",
    "Jeera Aloo",
    "Lauki Kofta",
    "Kadhi Pakora",
    "Vegetable Pulao",
    "Bhutte Ka Kees",
    "Poha Jalebi (Indore Special)",
    "Sabudana Vada",
    "Dal Puri",
    "Bafla Bati",
    "Indori Sev",
    "Garadu Chaat",
    "Khasta Kachori",
    "Chironji Ki Barfi",
    "Tilkut",
    "Dehrori (Chhattisgarh Sweet)",
    "Muthiya",
    "Aamat (Bamboo Shoot Curry)",
    "Farra (Steamed Dumplings)",

     # --- Northeast India (Variety) ---
    "Smoked Chicken Salad (Nagaland)",
    "Fish Cooked in Banana Leaf (Tripura)",
    "Kharisa (Bamboo Shoot Pickle)",
    "Eromba with Vegetables",
    "Phagshapa (Pork and Radish Stew)",
    "Chikhvi (Tripura Bamboo Shoot Stir Fry)",
    "Aloo Tomato Curry (Sikkimese)",
    "Rice Beer (Apong)",
    "Sticky Rice with Sesame",
    "Black Rice Pulao",

    # --- Street Foods (Pan-India) ---
    "Samosa",
    "Bread Pakora",
    "Pakora (Onion Fritters)",
    "Mirchi Bajji",
    "Cutlet",
    "Kathi Roll",
    "Egg Roll",
    "Paneer Roll",
    "Chicken Roll",
    "Momo Soup",
    "Tikki Chole",
    "Dahi Puri",
    "Sev Batata Puri",
    "Aloo Chat",
    "Corn Chaat",
    "Masala Peanuts",
    "Chana Jor Garam",
    "Keema Pav",
    "Anda Bhurji Pav",
    "Veg Puff",
    "Egg Puff",
    "Chicken Puff",
    "Schezwan Dosa",
    "Paneer Frankie",
    "Egg Frankie",
    "Pav Sandwich",
    "Veg Burger (Indian Style)",
    "Chinese Bhel",
    "Manchurian Fried Rice",
    "Tawa Pulao",
    "Hakka Noodles",
    "Gobi 65",
    "Paneer 65",
    "Masala Maggie",
    "Veg Momos Fried",
    "Steamed Momos",
    "Tandoori Momos",
    "Spring Rolls",
    "Paneer Chilli Dry",

    # --- Breads & Rotis ---
    "Tandoori Naan",
    "Tawa Roti",
    "Missi Roti",
    "Methi Paratha",
    "Lachha Paratha",
    "Rumali Roti",
    "Tandoori Kulcha",
    "Bhakri",
    "Phulka",
    "Jowar Roti",
    "Bajra Roti",
    "Poori",
    "Lucchi",
    "Khoba Roti",
    "Sheermal",
    "Taftan",
    "Rumali Naan",

    # --- Rice & Biryanis (Various States) ---
    "Lucknowi Biryani",
    "Calcutta Biryani",
    "Sindhi Biryani",
    "Kolkata Chicken Biryani",
    "Thalassery Biryani",
    "Beef Biryani Kerala",
    "Ambur Biryani",
    "Arcot Mutton Biryani",
    "Kacchi Biryani",
    "Mughlai Biryani",
    "Yakhni Pulao",
    "Vegetable Fried Rice",
    "Jeera Rice",
    "Ghee Rice",
    "Coconut Rice",
    "Peas Pulao",
    "Tawa Rice",
    "Veg Dum Biryani",
    "Egg Biryani",
    "Mushroom Biryani",
    "Jackfruit Biryani",
    "Paneer Biryani",

    # --- Snacks & Starters ---
    "Paneer Pakora",
    "Corn Pakora",
    "Spinach Pakora",
    "Aloo Bonda",
    "Veg Cutlet",
    "Mutton Cutlet",
    "Fish Cutlet",
    "Chicken Pakora",
    "Prawn Koliwada",
    "Chicken Lollipop",
    "Mutton Seekh Roll",
    "Veg Manchurian Dry",
    "Honey Chilli Potato",
    "Paneer Chilli Gravy",
    "Cabbage Pakora",
    "Bread Cutlet",
    "Moong Dal Pakodi",
    "Vegetable Samosa",
    "Mutton Shami Kebab",
    "Hara Bhara Kebab",


    # --- Dals ---
    "Dal Tadka",
    "Dal Makhani",
    "Panchmel Dal (Five Lentil Dal)",
    "Moong Dal Tadka",
    "Masoor Dal",
    

    # --- Desserts & Drinks ---
    "Gajar Ka Halwa",
    "Jalebi",
    "Gulab Jamun",
    "Kheer (Rice Pudding)",
    "Rasmalai",
    "Mango Lassi",
    "Masala Chai",
    "Kulfi",
    "Besan Ladoo",
    "Rava Ladoo",
    "Motichoor Ladoo",
    "Boondi Ladoo",
    "Kaju Katli",
    "Badam Halwa",
    "Sooji Halwa",
    "Moong Dal Halwa",
    "Atta Halwa",
    "Payasam",
    "Ada Pradhaman",
    "Parippu Payasam",
    "Chenna Murki",
    "Mohanthal",
    "Basundi",
    "Shrikhand (Amrakhand)",
    "Doodh Pak",
    "Patholi",
    "Kharvas",
    "Til Ladoo",
    "Tilgul",
    "Nolen Gur Rasgulla",
    "Rabri",
    "Falooda",
    "Ice Halwa",
    "Kulcha Halwa Combo",
    "Coconut Barfi",
    "Dry Fruit Barfi",
    "Chocolate Barfi",
    "Anjeer Barfi",
    "Khoya Peda",
    "Ras Kadam",
    "Sondesh (Nolen Gur)",
    "Cham Cham",
    "Balushahi",
    "Malpua",
    "Imarti",
    "Kesari Bath",
    "Halwasan",
    "Sheer Khurma",
    "Phirni",
    "Gond Ke Ladoo",
    "Tilkut",
    "Modak (Fried)",
    "Ukadiche Modak",
    "Gujiya",
    "Chhena Jalebi",
    "Patishapta",
    "Makhana Kheer",
    "Kesari Kheer",
    "Payesh",
    "Double Ka Meetha",
    "Shahi Tukda",
    "Sewaiyan",
    "Mysore Pak (Soft)",
    "Obbattu (Holige)",
    "Puran Poli (Different States)",
    "Banana Halwa",
    "Karachi Halwa",
    "Milk Cake",
    "Adhirasam",

    # --- Beverages ---
    "Filter Coffee",
    "South Indian Buttermilk (Neer Mor)",
    "Sweet Lassi",
    "Salted Lassi",
    "Badam Milk",
    "Thandai",
    "Aam Panna",
    "Jaljeera",
    "Shikanji",
    "Kokum Sharbat",
    "Sattu Drink",
    "Nimbu Soda",
    "Falooda Milkshake",
    "Cold Coffee",
    "Masala Milk",
    "Kesar Pista Milk",
    "Sol Kadhi",
    "Sugarcane Juice",
    "Tender Coconut Water",
    "Rose Milk",

    # --- Modern / Fusion & Regional Specialties ---
    "Paneer Tikka Pizza",
    "Butter Chicken Pasta",
    "Tandoori Momos",
    "Chicken Tikka Wrap",
    "Paneer Tikka Sandwich",
    "Masala Corn Toast",
    "Egg Curry Puff",
    "Masala Khichdi",
    "Palak Khichdi",
    "Sabudana Khichdi",
    "Moong Dal Khichdi",
    "Gujarati Khichdi Kadhi",
    "Bisi Bele Huli Anna",
    "Veg Stew with Appam",
    "Upkari (Konkani Dry Veg)",
    "Pathrode (Colocasia Roll)",
    "Ghee Roast Chicken",
    "Prawn Gassi",
    "Rava Fish Fry",
    "Kane Rava Fry",
    "Bangda Curry",
    "Tisrya Sukka (Clam Curry)",
    "Patra Ni Macchi",
    "Mutton Kheema Pav",
    "Egg Masala Curry",
    "Bhuna Gosht",
    "Tandoori Pomfret",
    "Butter Garlic Crab",
    "Rohu Fish Curry",
    "Catla Fish Curry",
    "Chicken Bharta",
    "Dum Mutton Curry",
    "Egg Masala Fry",
    "Aloo Jeera Dry",
    "Lauki Chana Dal",
    "Tinda Masala",
    "Arbi Fry",
    "Karela Fry",
    "Kachumber Salad",
    "Sprouts Salad",
    "Raj Kachori",
    "Veg Hakka Noodles",
    "Chicken Schezwan Rice",
    "Paneer Fried Rice",
    "Corn Fried Rice",
    "Veg Chowmein",
    "Egg Noodles",
    "Gobi Fried Rice"
]